[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "MobileDogs"
authors = [{name = "Kuzmin Ilia", email = "saharokbro@mail.ru"}, {name = "Nikiforova Darya", email = "darya.n.2004@mail.ru"}]
dynamic = ["version", "description"]
